Movies.Web/Controllers/MoviesCriteriaController.cs
using MovieModel.Criterias;
using Movies.Web.Classes;
using System.Web.Mvc;

namespace Movies.Web.Controllers
{
    public class MoviesCriteriaController : Controller
    {
        // GET: MoviesCriteria
       
        public ActionResult Filter(MoviesCriteria model)
        {
            return PartialView("moviescriteria", model);
        }

        public ActionResult Pager(MoviesCriteria model)
        {
            return PartialView("moviespages", model);
        }
        [HttpPost]
        public ActionResult ApplyFilter(MoviesCriteria model)
        {
            try
            {
                SessionVars.SetCriteria(model);
                model.Page = 1;
                return RedirectToAction("Index", "Movie");
            }
            catch
            {
                return View();
            }
        }

    }
}

Movies.Web/Controllers/PersonController.cs
using System.Web.Mvc;
using KnkInterfaces.Interfaces;
using MovieModel.Entities;
using MovieModel.Lists;

namespace Movies.Web.Controllers
{
    public class PersonController : Controller
    {
        // GET: Casting
        public ActionResult Index()
        {
            Utils.ConnectDatabase();
            return View("bestcasting");
        }

        // GET: Casting
        public ActionResult Popular()
        {
            Utils.ConnectDatabase();
            return View("popularcasting");
        }

        // GET: Casting
        public ActionResult Rated()
        {
            Utils.ConnectDatabase();
            return View("ratedcasting");
        }

        // GET: Casting/Details/5
        public ActionResult Details(int id)
        {
            Utils.ConnectDatabase();
            var lPerson = Utils.Connection().GetItem<Person>(id);
            return View("person", model: lPerson);
        }

        public ActionResult Thumbnail(Person person)
        {
            return PartialView("personthumb", model: person);
        }

        public ActionResult Casting(MovieCasting casting)
        {
            return PartialView("castingthumb", model: casting);
        }

        public ActionResult WorkedWith(int personid)
        {
            var persons = new Persons(personid);
            persons.Criteria.TopElements = 12;
            persons.SortAttribute = new KnkSortAttribute("WorkedTogether");
            persons.Sorting.Add(new KnkSortAttribute("Popularity"));
            return PartialView("persons", model: persons);
        }

        // GET: Casting/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Casting/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Casting/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Casting/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Movies.Web/Views/MoviesCriteria/moviescriteria.cshtml
@using MovieModel.Criterias
@using MovieModel.Lists
@using Microsoft.AspNet.Identity
@model MoviesCriteria
@{
    var lCri = Model;
    var elements = lCri.Elements;
    var listMovies = lCri.CurrentList();

    var listGenres = new Genres(listMovies.Connection);
    var lgenempty = listGenres.Create();
    lgenempty.GenreName = string.Empty;
    var genres = listGenres.Items.OrderBy(g => g.GenreName).ToDictionary(g => g.GenreName, g => g.GenreName);

    var listSagas = new MovieSets(listMovies.Connection);
    var lsagempty = listSagas.Create();
    lsagempty.Name = string.Empty;
    var sagas = listSagas.Items.OrderBy(g => g.Name).ToDictionary(g => g.Name, g => g.Name);

    var dicbool = new Dictionary<string, string>();
    dicbool.Add("true", "Ascendent");
    dicbool.Add("false", "Descendent");

    var dicnull = new Dictionary<string, string>();
    dicnull.Add("", "");
    dicnull.Add("true", "Yes");
    dicnull.Add("false", "No");

    var classlabel = "control-label text-primary";
    var classcontrol = "form-control";
}

@if (!lCri.IsRelated)
{
<div class="navbar-inverse">
    @if (!lCri.IsRelated)
    {
        using (Html.BeginForm("ApplyFilter", "MoviesCriteria", FormMethod.Post))
        {
            Html.AntiForgeryToken();
            <div class="col-md-3">
                <div class="col-md-2">
                    @Html.LabelFor(Model => Model.TextSearch, "Movie", new { @class = classlabel })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(Model => Model.TextSearch, new { @class = classcontrol })
                </div>
                <div class="col-md-2">
                    @Html.LabelFor(Model => Model.PersonName, "Artist", new { @class = classlabel })
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(Model => Model.PersonName, new { @class = classcontrol })
                </div>
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary">Apply</button>
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" style="width:100%">
                    <button class="btn btn-primary">Filter</button>
                </a>
            </div>
            if (!lCri.IsRelated)
            {
                <div class="col-md-4 btn-group">
                    @{Html.RenderAction("Pager", "MoviesCriteria", lCri); }
                </div>
                <div class="col-md-2"></div>
            }
            else
            {
                <div class="col-md-6"></div>
            }
            <div class="col-md-1 btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="width:100%">
                    Menu <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right multi-level" role="menu" aria-labelledby="dropdownMenu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Utils.CurrentUserId() != null)
                    {
                        <li class="divider"></li>
                        <li>@Html.ActionLink("Best Actors", "Index", "Person")</li>
                        <li>@Html.ActionLink("Popular Actors", "Popular", "Person")</li>
                        <li>@Html.ActionLink("Most Rated Actors", "Rated", "Person")</li>
                        <li>@Html.ActionLink("Recommendations from Actors", "ArtistRecommended", "Movie")</li>
                        <li class="divider"></li>
                        <li>@Html.ActionLink("Best Movies", "BestMovies", "Movie")</li>
                        <li>@Html.ActionLink("Last Updated", "LastUpdated", "Movie")</li>
                        <li>@Html.ActionLink("Last Viewed", "LastViewed", "Movie")</li>
                        <li>@Html.ActionLink("Most Viewed", "MostViewed", "Movie")</li>
                        <li>@Html.ActionLink("New Movies", "NewMovies", "Movie")</li>
                        <li>@Html.ActionLink("Next to see", "PendingMovies", "Movie")</li>
                        <li>@Html.ActionLink("Recomendations", "RecomendedMovies", "Movie")</li>
                        <li class="divider"></li>
                        <li>@Html.ActionLink("My Movies", "MyMovies", "Movie")</li>
                        <li>@Html.ActionLink("My Favourites", "FavouriteMovies", "Movie")</li>
                        <li>@Html.ActionLink("My Wishes", "WhisedMovies", "Movie")</li>
                    }
                    <li class="divider"></li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Welcome " + User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Close session</a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Login", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    }
                </ul>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body col-md-12">
                    <div class="row" style="padding:2px">
                        <div class="col-md-1">
                            @Html.LabelFor(Model => Model.Genre, new { @class = classlabel })
                        </div>
                        <div class="col-md-2">
                            @Html.DropDownListFor(Model => Model.Genre, new SelectList(genres, "Key", "Value", Model.Genre), new { @class = classcontrol })
                        </div>
                        <div class="col-md-1">
                            @Html.LabelFor(Model => Model.Saga, new { @class = classlabel })
                        </div>
                        <div class="col-md-2">
                            @Html.DropDownListFor(Model => Model.Saga, new SelectList(sagas, "Key", "Value", Model.Saga), new { @class = classcontrol })
                        </div>
                        <div class="col-md-1">
                            @Html.LabelFor(Model => Model.SortProperty, "Order by", new { @class = classlabel })
                        </div>
                        <div class="col-md-2">
                            @Html.DropDownListFor(Model => Model.SortProperty, new SelectList(MovieModel.Utilities.KnkSolutionMoviesUtils.MoviePropertiesCombo(Utils.CurrentUserId()), "Value", "Key", Model.SortProperty), new { @class = classcontrol })
                        </div>
                        <div class="col-md-1">
                            @Html.LabelFor(Model => Model.SortDirectionAsc, "Direction", new { @class = classlabel })
                        </div>
                        <div class="col-md-2">
                            @Html.DropDownListFor(Model => Model.SortDirectionAsc, new SelectList(dicbool, "Key", "Value", Model.SortDirectionAsc), new { @class = classcontrol })
                        </div>
                    </div>
                    @if (Utils.CurrentUserId() != null)
                    {
                        <div class="row" style="padding:2px">
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.InMyLib, "In My Lib", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.DropDownListFor(Model => Model.InMyLib, new SelectList(dicnull, "Key", "Value", Model.InMyLib), new { @class = classcontrol })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.HasFiles, "Has Files", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.DropDownListFor(Model => Model.HasFiles, new SelectList(dicnull, "Key", "Value", Model.HasFiles), new { @class = classcontrol })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.HasLink, "Has Link", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.DropDownListFor(Model => Model.HasLink, new SelectList(dicnull, "Key", "Value", Model.HasLink), new { @class = classcontrol })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.Viewed, new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.DropDownListFor(Model => Model.Viewed, new SelectList(dicnull, "Key", "Value", Model.Viewed), new { @class = classcontrol })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.UserRated, "User Rated", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.DropDownListFor(Model => Model.UserRated, new SelectList(dicnull, "Key", "Value", Model.UserRated), new { @class = classcontrol })
                            </div>
                        </div>
                        <div class="row" style="padding:2px">
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.YearFrom, "Year", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.YearFrom, new { @class = classcontrol, type = "number", min = 1800, max = DateTime.Now.Year })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.YearTo, new { @class = classcontrol, type = "number", min = 1800, max = DateTime.Now.Year })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.RatingFrom, "Rating", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.RatingFrom, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.RatingTo, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.UserRatingFrom, "User Rating", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.UserRatingFrom, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.UserRatingTo, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                            <div class="col-md-1">
                                @Html.LabelFor(Model => Model.PredictedRatingFrom, "Predicted Rating", new { @class = classlabel })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.PredictedRatingFrom, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                            <div class="col-md-1">
                                @Html.TextBoxFor(model => model.PredictedRatingTo, "{0:n2}", new { @class = classcontrol, type = "decimal", min = 0, max = 10 })
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    }
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
    }
</div>
}

Movies.Web/Views/MoviesCriteria/moviespages.cshtml
@using MovieModel.Criterias
@model MoviesCriteria
@{
    var lCri = Model;
    var elements = lCri.Elements;
    var listMovies = lCri.CurrentList();
    var lNumberPages = Convert.ToInt16(Math.Ceiling((decimal)listMovies.Items.Count() / elements));
    var lPagines = 5;
    var fromitm = lCri.Page - 3;
    while (fromitm <= 0)
    {
        fromitm++;
    }
    var toitm = fromitm + lPagines;
    while (toitm > lNumberPages)
    {
        toitm--;
        if (fromitm > 1)
        {
            fromitm--;
        }
    }

}
@if (lNumberPages > 1)
{
    Session["Criteria"] = KnkCore.Utilities.KnkCoreUtils.XmlSerializeObject<MoviesCriteria>(lCri);
    <div class="col-md-1"></div>
    <div class="col-md-10 container-fluid text-center row">
        <ul class="pagination justify-content-end" id="pagination-custom" style="margin:5px;">
            @if (lCri.Page > 1)
            {
                <li>@Html.ActionLink($"First", "MoviesPaged", "Movie", new { Page = 1 }, new { @class = "page-item", @id= "page-item-custom" })</li>
                <li>@Html.ActionLink($"Previous", "MoviesPaged", "Movie", new { Page = lCri.Page - 1 }, new { @class = "page-item", @id = "page-item-custom" })</li>
            }
            @for (int i = fromitm; i <= toitm; i++)
            {
                if (i == lCri.Page)
                {
                    <li class="page-item active">
                        <a href=@Url.Action("MoviesPaged", "Movie", new { Page = i })><span class="page-link">@i</span></a>
                    </li>
                }
                else
                {
                    <li>@Html.ActionLink($"{i}", "MoviesPaged", "Movie", new { Page = i }, new { @class = "page-item", @id = "page-item-custom" })</li>
                }
            }
            @if (lNumberPages > lCri.Page)
            {
                <li>@Html.ActionLink($"Next", "MoviesPaged", "Movie", new { Page = lCri.Page + 1 }, new { @class = "page-item", @id = "page-item-custom" })</li>
                <li>@Html.ActionLink($"Last {lNumberPages}", "MoviesPaged", "Movie", new { Page = lNumberPages }, new { @class = "page-item", @id = "page-item-custom" })</li>
            }
        </ul>
    </div>
}