Movies.Web/Controllers/CommentController.cs
using MovieModel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movies.Web.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult MovieComments(Movie aMovie)
        {
            return View(aMovie);
        }

        [HttpPost]
        public ActionResult Addcomment(string commenttext, int? idmovie, int? idcomment)
        {
            //var type = Type.GetType($"{comment.Object},MovieModel");
            dynamic owner = null;
            if(idmovie != null)
                owner = Utils.Connection().GetItem<Movie>(idmovie);
            else
                owner = Utils.Connection().GetItem<Comment>(idcomment);

            Comment comment = owner.Comments().Create();
            comment.IdMovieOwner = idmovie;
            comment.IdCommentOwner = idcomment;
            comment.CommentText = commenttext;
            comment.CreationDate = DateTime.Now;
            comment.UserCreationId = Utils.CurrentUser().IdUser;
            comment.Update("Created Comment");
            comment.SaveChanges();

            var lObj = owner;

            while (lObj is Comment)
            {
                if (lObj.ItemOwner == null)
                    break;
                else
                    lObj = lObj.ItemOwner;
            }
            return RedirectToAction("MovieComments", "Movie", new { id = lObj.PrimaryKeyValue().Value });
        }

    }
}

Movies.Web/Controllers/PersonController.cs
using System.Web.Mvc;
using KnkInterfaces.Interfaces;
using MovieModel.Entities;
using MovieModel.Lists;

namespace Movies.Web.Controllers
{
    public class PersonController : Controller
    {
        // GET: Casting
        public ActionResult Index()
        {
            Utils.ConnectDatabase();
            return View("bestcasting");
        }

        // GET: Casting
        public ActionResult Popular()
        {
            Utils.ConnectDatabase();
            return View("popularcasting");
        }

        // GET: Casting
        public ActionResult Rated()
        {
            Utils.ConnectDatabase();
            return View("ratedcasting");
        }

        // GET: Casting/Details/5
        public ActionResult Details(int id)
        {
            Utils.ConnectDatabase();
            var lPerson = Utils.Connection().GetItem<Person>(id);
            return View("person", model: lPerson);
        }

        public ActionResult Thumbnail(Person person)
        {
            return PartialView("personthumb", model: person);
        }

        public ActionResult Casting(MovieCasting casting)
        {
            return PartialView("castingthumb", model: casting);
        }

        public ActionResult WorkedWith(int personid)
        {
            var persons = new Persons(personid);
            persons.Criteria.TopElements = 12;
            persons.SortAttribute = new KnkSortAttribute("WorkedTogether");
            persons.Sorting.Add(new KnkSortAttribute("Popularity"));
            return PartialView("persons", model: persons);
        }

        // GET: Casting/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Casting/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Casting/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Casting/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Movies.Web/Views/Shared/DisplayTemplates/castinglist.cshtml
@model IEnumerable<MovieModel.Entities.MovieCasting>
@{
    var list = Model;
}
@if (list != null)
{
    var i = 0;
    var movie = list.FirstOrDefault();
    foreach (var lArt in list)
    {
        if (i > 0)
        {
            @Html.Raw(", ");
        }
        <a href=@Url.Action("Details", "Person", new { id = @lArt.IdPerson.Value ?? 0 })><b>@lArt.IdPerson.Reference.ToString()</b></a>
        i++;
    }
    if (movie != null)
    {
        @Html.Raw(", ");
        <a href=@Url.Action("MovieCasting", "Movie", new { id = @movie.IdMovie ?? 0 })><b>(Full Casting)</b></a>
    }
}

Movies.Web/Views/Shared/DisplayTemplates/castingsepthumb.cshtml
@model string
<div class="knkcastingthumb" style="background-color:#333333;">
    <div class="thumbnail knkcastingsmall img-rounded">
        <p class="text-center text-nowrap h1 vcenter" style="width:100%;height:100%;display:inline-block;color:#222"><b>@Model</b></p>
    </div>
</div>

Movies.Web/Views/Shared/DisplayTemplates/comment-non.cshtml
@model MovieModel.Entities.Comment
@{
    var comment = Model;
    var author = string.Empty;
    var iduser = comment?.UserCreationId?.Value ?? Utils.CurrentUserId();
    var usu = comment.Connection().GetItem<MovieModel.Entities.User>(iduser);
    var comments = comment.Comments();
    var isnew = comment.IsNew();
    var colapseid = "";
    var colapseidref = $"#collapse{comment.IdComment}";
    var itemowner = comment.ItemOwner;
    var divclass = "comment-main-level";
    var newcom = comment;
    if (isnew)
    {
        colapseid= $"#collapse{itemowner.PrimaryKeyValue()}";
        divclass = divclass + " panel-collapse";
        if (comment.Object == comment.GetType().ToString())
        {
            divclass = divclass + " collapse";
        }
    }
    else
    {
        newcom = comment.Comments().Create();
        newcom.ItemOwner = comment;
        newcom.UserCreationId = Utils.CurrentUser().IdUser;
        if (comment.UserCreationId.Value == Utils.CurrentUserId())
        {
            author = "by-author";
        }
    }
}
<li>
    <div class="col-md-12 row">
        @*we should toggle the hidden comment when needed*@
        <div id=@colapseid class="@divclass"> 
            <div class="row">
                <div class="col-md-1">
                    <div class="comment-avatar"><img src=@Url.Content("~/Resources/46-512.png") alt="Image" width="80" height="80"></div>
                </div>
                <div class="col-md-11">
                    <div class="comment-box">
                        @if (!isnew)
                        {
                            <div class="comment-head">@comment.CommentText</div>
                            <div class="comment-content">
                                <h6 class="comment-name">@comment.CreationDate</h6>
                                <h6 class="comment-name @author">@usu.ToString()</h6>
                                <a data-toggle="collapse" data-parent="#accordion" href=@colapseidref>
                                    <i class="fa fa-reply"></i>
                                </a>
                                <i class="fa fa-thumbs-o-down"></i>
                                <i class="fa fa-thumbs-o-up"></i>
                            </div>
                        }
                        else
                        {
                            using (Html.BeginForm("AddComment", "Comment", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <div class="comment-head">
                                    @Html.Hidden("Object", comment.Object)
                                    @Html.Hidden("IdValue", comment.IdValue.Value)
                                    @Html.TextArea("CommentText", comment.CommentText, 2, 0, new { @style = "min-width:100%" })
                                    @Html.Hidden("CreationUserId", comment.UserCreationId.Value)
                                </div>
                                @*<div class="comment-content">
                                    <button type="submit" class="btn btn-primary" style="width:100%">Añadir</button>
                                </div>*@
                                <div class="comment-content">
                                    <h6 class="comment-name">@comment.CreationDate</h6>
                                    <h6 class="comment-name @author">@usu.ToString()</h6>
                                    <a data-toggle="collapse" data-parent="#accordion" href=@colapseidref>
                                        <i class="fa fa-reply"></i>
                                    </a>
                                    <i class="fa fa-thumbs-o-down"></i>
                                    <i class="fa fa-thumbs-o-up"></i>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        @if (comments.Count() > 0)
        {
            <ul class="comments-list reply-list">
                @foreach (var com in comments.Items)
                {
                    @Html.DisplayFor(d => com, "comment");
                }
            </ul>
        }
    </div>
    @Html.DisplayFor(d => newcom, "comment");
</li>

Movies.Web/Views/Shared/DisplayTemplates/comment.cshtml
@model MovieModel.Entities.Comment
@{
    var comment = Model;
    var isroot = comment.IdMovieOwner!=null;
    var iduser = comment?.UserCreationId?.Value ?? Utils.CurrentUserId();
    var usu = comment.Connection().GetItem<MovieModel.Entities.User>(iduser);
    var comments = comment.Comments();
    var isnew = comment.IsNew();
    var colapseid = "";
    var colapseidref = $"#collapse{comment.IdComment}";
    var itemowner = comment.ItemOwner;
    var divsmall = "col-xs-1 col-md-1 col-lg-1";
    var divlarge = "col-xs-11 col-md-11 col-lg-11";
    var divclass = divlarge;
    var level = $"{25 * comment.CommentLevel}px";
    var newcom = comment;
    var comdate = string.Empty;
    var formname = $"form{itemowner.PrimaryKeyValue()}";
    var formnameidmovie = $"idmovie";
    var formnameidcomment = $"idcomment";
    var formnamecomment = $"commenttext";
    if (isnew)
    {
        if (!isroot)
        {
            colapseid = $"collapse{itemowner.PrimaryKeyValue()}";
            divclass = divclass + " panel-collapse collapse";
        }
    }
    else
    {
        comdate = comment.CreationDate.Value.ToLongDateString() + " a las " + comment.CreationDate.Value.ToLongTimeString();
        newcom = comment.Comments().Create(false);
        newcom.IdCommentOwner = comment;
        newcom.UserCreationId = Utils.CurrentUser().IdUser;
    }
}
<div id=@colapseid class="@divclass" style="margin-left:@level">
    <div class="row col-md-12">
        <div class=@divsmall>
            <div class="comment-avatar"><img src=@Url.Content("~/Resources/46-512.png") alt="Image" width="48" height="48"></div>
        </div>
        <div class="@divlarge nopadding">
            <div class="row col-md-12">
                @if (!isnew)
                {
                    <div class="@divsmall text-center nopadding">
                        <a data-toggle="collapse" data-parent="#accordion" href=@colapseidref>
                            <i class="fa fa-reply"></i>
                        </a><br />
                        <i class="fa fa-thumbs-o-down"></i>
                        <i class="fa fa-thumbs-o-up"></i>
                    </div>
                    <div class="@divlarge nopadding">
                        <p>@comment.CommentText</p>
                        <h6>@usu.ToString() - @comdate</h6>
                    </div>
                }
                else
                {
                    using (Html.BeginForm("AddComment", "Comment", FormMethod.Post, new { enctype = "multipart/form-data", id = formname, Name = formname }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="@divlarge nopadding">
                            @Html.TextArea("commenttext", comment.CommentText, 2, 0, new { id = formnamecomment, Name = formnamecomment, style = "min-width:100%" })
                            @Html.Hidden("idmovie", comment.IdMovieOwner?.Value, new { id = formnameidmovie, Name = formnameidmovie })
                            @Html.Hidden("idcomment", comment.IdCommentOwner?.Value, new { id = formnameidcomment, Name = formnameidcomment })
                        </div>
                        <div class="@divsmall nopadding">
                            <button type="submit" class="btn btn-primary nopadding">Añadir</button>
                        </div>
                    }
                }
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
@if (!isnew)
{
    @Html.DisplayFor(d => newcom, "comment");
    if (comments.Count() > 0)
    {
        foreach (var com in comments.Items)
        {
            @Html.DisplayFor(d => com, "comment");
        }
    }
}

@*@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
}*@

Movies.Web/Views/Shared/DisplayTemplates/selectcontrol.cshtml
@model string
<p class="btn btn-primary" style="width:100%"><b>Model</b></p>

Movies.Web/Views/Shared/DisplayTemplates/separator.cshtml
@model Tuple<string, string>
<p class="btn btn-primary" style="width:100%;background-color:#222222;border:none;">
    <b>@Model.Item1
    @if (!string.IsNullOrEmpty(@Model.Item2))
    {
        @Html.Raw("&nbsp")
        <a href=@Model.Item2 style="color:antiquewhite" target="_blank">@Model.Item2</a>
    }
</b>
</p>