Movies.Web/Controllers/MovieController.cs
using System.Linq;
using System.Web.Mvc;
using MovieModel.Entities;
using MovieModel.Criterias;
using System;
using Movies.Web.Classes;

namespace Movies.Web.Controllers
{
    public class MovieController : Controller
    {
        public ActionResult Index()
        {
            return View("movies");
        }

        public ActionResult MoviesInitial()
        {
            SessionVars.SetCriteria(SessionVars.DefaultCriteria());
            return PartialView("movies");
        }

        public ActionResult Movies()
        {
            return PartialView("movies");
        }

        public ActionResult Movies(MoviesCriteria moviesCriteria)
        {
            return PartialView("movies", moviesCriteria);
        }

        public ActionResult MoviesView(MoviesCriteria moviesCriteria)
        {
            return View("movies", moviesCriteria);
        }

        public ActionResult BestMovies()
        {
            var criteria=new MoviesCriteria();
            criteria.BestMovies();
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult MyMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.MyMovies(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult FavouriteMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.FavouriteMovies(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult WhisedMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.WhisedMovies(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult RecomendedMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.Recomendations(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult PendingMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.PendingMovies(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult ArtistRecommended()
        {
            var criteria = new MoviesCriteria();
            criteria.ArtistRecommended(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult NewMovies()
        {
            var criteria = new MoviesCriteria();
            criteria.NewMovies(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult LastUpdated()
        {
            var criteria = new MoviesCriteria();
            criteria.LastUpdates(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult LastViewed()
        {
            var criteria = new MoviesCriteria();
            criteria.LastViewed(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult MostViewed()
        {
            var criteria = new MoviesCriteria();
            criteria.MostViewed(Utils.CurrentUserId());
            SessionVars.SetCriteria(criteria);
            return Index();
        }

        public ActionResult Artist(string Artist)
        {
            SessionVars.SetCriteria(new MoviesCriteria(personname: Artist) { CriteriaTitle = $"{Artist} Movies" });
            return Index();
        }

        public ActionResult PersonId(int PersonId)
        {
            return Movies(new MoviesCriteria(personid: PersonId) { InfoValue = $"MovieCasting.Role:{PersonId}" });
        }

        public ActionResult Saga(string MovieSet)
        {
            return Movies(new MoviesCriteria(saga: MovieSet) { CriteriaTitle = $"{MovieSet} Movies", SortDirectionAsc = true });
        }

        public ActionResult MovieSet(string MovieSet)
        {
            return MoviesView(new MoviesCriteria(saga: MovieSet) { CriteriaTitle = $"{MovieSet} Movies" });
        }

        public ActionResult MoviesRelated(int movie)
        {
            return Movies(new MoviesCriteria(movie: movie) { SortProperty = "PredictedRating", Rows = 2, Viewed=false, AllowNavigate=false });
        }

        public ActionResult Country(string Country)
        {
            SessionVars.SetCriteria(new MoviesCriteria(country: Country) { CriteriaTitle = $"{Country} Movies" });
            return Index();
        }

        public ActionResult Company(string Company)
        {
            SessionVars.SetCriteria(new MoviesCriteria(company: Company) { CriteriaTitle = $"{Company} Movies" });
            return Index();
        }

        public ActionResult Keyword(string Keyword)
        {
            SessionVars.SetCriteria(new MoviesCriteria(keyword: Keyword) { CriteriaTitle = $"Keyword {Keyword} Movies" });
            return Index();
        }

        public ActionResult Genre(string Genre)
        {
            SessionVars.SetCriteria(new MoviesCriteria(genre: Genre) { CriteriaTitle = $"{Genre} Movies" });
            return Index();
        }

        public ActionResult Year(int Year)
        {
            SessionVars.SetCriteria(new MoviesCriteria(year: Year) { CriteriaTitle = $"{Year} Movies" });
            return Index();
        }

        public ActionResult RelatedMovies(int movieid, string title)
        {
            SessionVars.SetCriteria(new MoviesCriteria(movie: movieid) { CriteriaTitle = $"Related {title} Movies" });
            return Index();
        }

        public ActionResult WorkedTogheter(int PersonId1, int PersonId2)
        {
            var person1 = Utils.Connection().GetItem<Person>(PersonId1);
            var person2 = Utils.Connection().GetItem<Person>(PersonId2);
            SessionVars.SetCriteria(new MoviesCriteria(personid1: PersonId1, personid2: PersonId2) { CriteriaTitle = $"{person1.Name} Worked with {person2.Name}" });
            return Index();
        }

        public ActionResult MoviesPaged(int Page)
        {
            MoviesCriteria criteria = SessionVars.GetCriteria();
            criteria.Page = Page;
            SessionVars.SetCriteria(criteria);
            return Index();
        }
       
        // GET: Movie/Details/5
        public ActionResult Details(int id)
        {
            Utils.ConnectDatabase();
            var lMovie = Utils.Connection().GetItem<Movie>(id);
            return View("movie", model: lMovie);
        }

        // GET: Movie/Details/5
        public ActionResult Thumbnail(Movie movie)
        {
            return PartialView("moviethumb", model: movie);
        }

        public ActionResult DetailsLink(int id, bool enablelink)
        {
            var lMovies = new MovieModel.Lists.Movies();
            var lMovie = lMovies.Connection.GetItem<Movie>(id);
            var lUsu = Utils.CurrentUserId();
            if (lUsu != null && enablelink)
            {
                Utils.ELinkEnabled(HttpContext.Request.UserHostAddress, lMovies.Connection.GetItem<User>(lUsu), lMovie);
                if(!lMovie.Users().Items.Any(u=>u.IdUser==lUsu))
                {
                    var lUsm = lMovie.Users().Create();
                    lUsm.IdMovie = id;
                    lUsm.IdUser = lUsu;
                    lUsm.Update("Imported " + HttpContext.Request.UserHostAddress);
                    lUsm.SaveChanges();
                }
                ViewBag.EnableLink = enablelink;
            }
            else
                ViewBag.EnableLink = false;
            return View("movie", model: lMovie);
        }

        public ActionResult AddViewed(int movie_id, int? file_id)
        {
            var lMovie = Utils.Connection().GetItem<Movie>(movie_id);
            var lUsu = Utils.CurrentUserId();
            if (lUsu != null)
            {
                if (!lMovie.Views().Items.Any(v => v.DateEnd.HasValue && v.DateEnd.Value.Date == DateTime.Now.Date))
                {
                    File lFile = null;
                    if (file_id != null) lMovie.Connection().GetItem<File>(file_id);
                    var duration = lFile?.Duration ?? (lMovie?.Duration ?? new TimeSpan(2, 0, 0));
                    var lView = lMovie.Views().Create();
                    lView.IdMovie = lMovie;
                    lView.IdFile = file_id;
                    lView.DateEnd = DateTime.Now;
                    lView.DateStart = lView.DateEnd.Value;
                    lView.DateStart = lView.DateStart.Subtract(duration);
                    lView.CurrentTime = duration;
                    lView.Update("Registered Manually View");
                    lView.SaveChanges();
                }
            }
            return RedirectToAction("Details", new { id = movie_id });
        }

        public ActionResult DeleteViewed(int movieid, int viewid)
        {
            var movie = Utils.Connection().GetItem<Movie>(movieid);
            var view = movie.Views().Items.FirstOrDefault(v => v.IdView == viewid);
            if (view != null)
            {
                view.Delete("Deleted");
                view.SaveChanges();
            }
            return RedirectToAction("Details", new { id = movieid });
        }

        public ActionResult MovieCasting(int id)
        {
            var lMovies = new MovieModel.Lists.Movies();
            var lMovie = lMovies.Connection.GetItem<Movie>(id);
            return View("moviecasting", lMovie);
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        [HttpPost]

Movies.Web/Controllers/PersonController.cs
using System.Web.Mvc;
using KnkInterfaces.Interfaces;
using MovieModel.Entities;
using MovieModel.Lists;

namespace Movies.Web.Controllers
{
    public class PersonController : Controller
    {
        // GET: Casting
        public ActionResult Index()
        {
            Utils.ConnectDatabase();
            return View("bestcasting");
        }

        // GET: Casting
        public ActionResult Popular()
        {
            Utils.ConnectDatabase();
            return View("popularcasting");
        }

        // GET: Casting
        public ActionResult Rated()
        {
            Utils.ConnectDatabase();
            return View("ratedcasting");
        }

        // GET: Casting/Details/5
        public ActionResult Details(int id)
        {
            Utils.ConnectDatabase();
            var lPerson = Utils.Connection().GetItem<Person>(id);
            return View("person", model: lPerson);
        }

        public ActionResult Thumbnail(Person person)
        {
            return PartialView("personthumb", model: person);
        }

        public ActionResult Casting(MovieCasting casting)
        {
            return PartialView("castingthumb", model: casting);
        }

        public ActionResult WorkedWith(int personid)
        {
            var persons = new Persons(personid);
            persons.Criteria.TopElements = 12;
            persons.SortAttribute = new KnkSortAttribute("WorkedTogether");
            persons.Sorting.Add(new KnkSortAttribute("Popularity"));
            return PartialView("persons", model: persons);
        }

        // GET: Casting/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Casting/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Casting/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Casting/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Casting/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Movies.Web/Views/Person/bestcasting.cshtml
@using MovieModel.Lists
@using System.Linq
@model Persons
@{
    Utils.ConnectDatabase();
    var persons = new Persons();
    var auxsep = new Tuple<string, string>("Casting Scraped From", "https://www.themoviedb.org/");
    ViewBag.Title = $"Best Actors";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="col-md-12">
    @Html.DisplayFor(d => auxsep, "separator")
    @{
        var items = 0;
        if (Utils.CurrentUserId() > 0)
        {
            items = 9 * 5 * 5;
        }

        var lCast = new List<MovieModel.Entities.Person>();

        if (items > 0)
        {
            lCast = (from cst in persons.Items
                     where cst.RatedMovies > 2
                     orderby cst.UserRating descending, cst.RatedMovies descending
                     select cst).Take(items).ToList();
            foreach (var cst in lCast)
            {
                @Html.Action("Thumbnail", "Person", new { person = cst })
            }
        }
    }
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies.Web/Views/Person/castingthumb.cshtml
@model MovieModel.Entities.MovieCasting
@{
    var person = Model.IdPerson.Reference;
    var role = Model.Role;
    var searchperson = $"https://www.google.com/search?q={Uri.EscapeDataString(person.Name)}&tbm=isch";
    var searchrole = $"https://www.google.com/search?q={Uri.EscapeDataString(person.Name + " " + Model.IdMovie.Reference.Title)}&tbm=isch";
    List<string> lMsg = new List<string>();
    string lTxt = string.Empty;
    if (person.Movies != null)
    {
        lMsg.Add($"M {person.Movies}");
    }
    if (Utils.CurrentUserId() != null)
    {
        if (person.RatedMovies != null)
        {
            lMsg.Add($"R {person.RatedMovies}");
        }
        if (person.UserRating != null)
        {
            lMsg.Add($"U {person.UserRating:0.0}");
        }
        if (person.Popularity != null)
        {
            lMsg.Add($"P {person.Popularity:0.0}");
        }
    }
    if (lMsg.Count > 0)
    {
        lTxt = lMsg.Aggregate((i, j) => i + " " + j);
    }

}
<div class="knkcastingthumb">
    @if (person.Extender.Poster == null)
    {
        <a class="thumbnail knkcastingsmall img-rounded" href=@Url.Action("Details", "Person", new { id = person.IdPerson.Value ?? 0 }) style="background-color:lightblue">
        </a>
    }
    else
    {
        <a class="thumbnail knkcastingsmall img-rounded" href=@Url.Action("Details", "Person", new { id = person.IdPerson.Value ?? 0 })>
            <img class="img-rounded" src=@person.Extender.Poster width="100%" height="100%" style="min-height:100%;" />
        </a>
    }
    <p class="text-center text-nowrap" style="width:100%;display:inline-block">
        <b><a href=@searchperson target="_blank">@person.Name</a></b><br />
        @lTxt
        @if (!string.IsNullOrEmpty(role))
        {
            <br /><a href=@searchrole target="_blank">@role</a>
        }
    </p>
</div>

Movies.Web/Views/Person/person.cshtml
@using System.Linq
@model MovieModel.Entities.Person
@{
    Utils.ConnectDatabase();
    var person = Model;
    var auxsep = new Tuple<string, string>("Artist Scraped From", "https://www.themoviedb.org/");
    var auxwor = new Tuple<string, string>("Worked with", "https://www.themoviedb.org/");
    var searchstr = $"https://www.google.com/search?q={Uri.EscapeDataString(person.Name)}&tbm=isch";
    var searchtmdp = $"https://www.themoviedb.org/person/{person.TmdbId}";
    var searchimdb = $"https://www.imdb.com/search/name?name={Uri.EscapeDataString(person.Name)}";
    if (!string.IsNullOrEmpty(person.ImdbId))
    {
        searchimdb = $"https://www.imdb.com/name/{person.ImdbId}/";
    }
    ViewBag.Title = person.Name;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-4">
        <img src=@person.Extender.Poster width="100%" />
        <div class="col-md-12" style="padding:0px;border-top-style:solid;border-top-width:1px;">
            @Html.DisplayFor(d => auxwor, "separator")
            @Html.Action("WorkedWith", "Person", new { personId = person.IdPerson.Value })
        </div>
    </div>
    <div class="col-md-8 knkmoviesinfo">
        <dl class="dl-horizontal">
            <dt>&nbsp;</dt>
            <dd>&nbsp;</dd>
            <dt>Artist</dt>
            <dd><a href=@searchstr target="_blank">@person.Name</a></dd>
            @if (!string.IsNullOrEmpty(person.BirthDay))
            {
                <dt>Birthday</dt>
                <dd>@person.BirthDay</dd>
            }
            @if (!string.IsNullOrEmpty(person.BirthPlace))
            {
                <dt>BirthPlace</dt>
                <dd>@person.BirthPlace</dd>
            }
            @if (!string.IsNullOrEmpty(person.HomePage))
            {
                <dt>HomePage</dt>
                <dd>@person.HomePage</dd>
            }
            <dt>&nbsp;</dt>
            <dd>&nbsp;</dd>
            <dt>Scraped Date</dt>
            <dd>@person.ScrapedDate</dd>
            <dt>Tmdb</dt>
            <dd><a href=@searchtmdp target="_blank">Tmdb: @person.Name</a></dd>
            <dt>Imdb</dt>
            <dd><a href=@searchimdb target="_blank">Imdb: @person.Name</a></dd>
            @if (person.Movies != null)
            {
                <dt>Movies</dt>
                <dd>@person.Movies</dd>
            }
            @if (person.Popularity != null)
            {
                <dt>Popularity</dt>
                <dd>@person.Popularity</dd>
            }
            <dt>Rating</dt>
            <dd>@Html.MweStarRating(person.Rating)</dd>
            @if (person.RatedMovies != null && Utils.IsLoggedUser())
            {
                <dt>Movies Rated</dt>
                <dd>@person.RatedMovies</dd>
            }
            @if (person.UserRating != null && Utils.IsLoggedUser())
            {
                <dt>User Rating</dt>
                <dd>@Html.MweStarRating(person.UserRating)</dd>
            }
            <dt>&nbsp;</dt>
            <dd>&nbsp;</dd>
            @if (!string.IsNullOrEmpty(person.Extender.Biography))
            {
                <dt>Biography</dt>
                <dd>@person.Extender.Biography</dd>
            }
        </dl>
    </div>
    <div class="col-md-8" style="border-top-style:solid;border-top-width:1px;padding:0px;">
        @Html.DisplayFor(d => auxsep, "separator")
        <div class="col-md-12" style="border-top-style:solid;border-top-width:1px;padding:0px;">
            @Html.Action("PersonId", "Movie", new { PersonId = person.IdPerson.Value })
        </div>
    </div>
}

Movies.Web/Views/Person/persons.cshtml
@using MovieModel.Lists
@using System.Linq
@model Persons
@{
    Utils.ConnectDatabase();
    var auxsep = new Tuple<string, string>("Artists Scraped From", "https://www.themoviedb.org/");
    var list = Model;
    var lCast = (from cst in list.Items
                 orderby cst.WorkedTogether descending, cst.Popularity descending
                 select cst).ToList();
}

@using (Html.BeginForm())
{
<div class="col-md-12 knkmoviescontainer" style="padding:0px;border-top-style:solid;border-top-width:1px;">
    @foreach (var cst in lCast)
    {
        @Html.Action("Thumbnail", "Person", new { person = cst })
    }
</div>
}

Movies.Web/Views/Person/personthumb.cshtml
@model MovieModel.Entities.Person
@{
    var person = Model;
    var searchperson = $"https://www.google.com/search?q={Uri.EscapeDataString(person.Name)}&tbm=isch";
    List<string> lMsg = new List<string>();
    string lTxt = string.Empty;
    string idaux = person.GetParent<MovieModel.Entities.Person, MovieModel.Entities.Person>()?.Criteria?.GetParameters()?.FirstOrDefault()?.Value;
    int? idpersonparent = null;
    if (person.WorkedTogether.HasValue && !string.IsNullOrEmpty(idaux)) {
        idpersonparent = int.Parse(idaux);
    }
    if (person.Movies != null)
    {
        lMsg.Add($"M {person.Movies}");
    }
    if (Utils.CurrentUserId() != null)
    {
        if (person.RatedMovies != null)
        {
            lMsg.Add($"R {person.RatedMovies}");
        }
        if (person.UserRating != null)
        {
            lMsg.Add($"U {person.UserRating:0.0}");
        }
        if (person.Popularity != null)
        {
            lMsg.Add($"P {person.Popularity:0.0}");
        }
    }
    if (lMsg.Count > 0)
    {
        lTxt = lMsg.Aggregate((i, j) => i + " " + j);
    }

}
<div class="knkcastingthumb">
    @if (person.Extender.Poster == null)
    {
        <a class="thumbnail knkcastingsmall img-rounded" href=@Url.Action("Details", "Person", new { id = person.IdPerson.Value ?? 0 }) style="background-color:lightblue">
        </a>
    }
    else
    {
        <a class="thumbnail knkcastingsmall img-rounded" href=@Url.Action("Details", "Person", new { id = person.IdPerson.Value ?? 0 })>
            <img class="img-rounded" src=@person.Extender.Poster width="100%" height="100%" style="min-height:100%;" />
        </a>
    }
        <p class="text-center text-nowrap" style="width:100%;display:inline-block">
            <b><a href=@searchperson target="_blank">@person.Name</a></b><br />
            @lTxt
            @if (person.WorkedTogether.HasValue)
            {
                <br />
                if (idpersonparent.HasValue)
                {
                    <a href=@Url.Action("WorkedTogheter", "Movie", new { PersonId1 = idpersonparent, PersonId2 = person.IdPerson.Value }) target="_blank">
                        @Html.Raw($"Worked {person.WorkedTogether} times")
                    </a>
                }
                else
                {
                    @Html.Raw($"Worked {person.WorkedTogether} times")
                }
            }
        </p>
</div>

Movies.Web/Views/Person/popularcasting.cshtml
@using MovieModel.Lists
@using System.Linq
@model Persons
@{
    Utils.ConnectDatabase();
    var persons = new Persons();
    var auxsep = new Tuple<string, string>("Casting Scraped From", "https://www.themoviedb.org/");
    ViewBag.Title = $"Popular Actors";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="col-md-12">
    @Html.DisplayFor(d => auxsep, "separator")
    @{
        var items = 0;
        if (Utils.CurrentUserId() > 0)
        {
            items = 9 * 5;
        }

        var lCast = new List<MovieModel.Entities.Person>();

        if (items > 0)
        {
            lCast = (from cst in persons.Items
                     orderby cst.Popularity descending, cst.RatedMovies descending
                     select cst).Take(items * 5).ToList();


            foreach (var cst in lCast)
            {
                @Html.Action("Thumbnail", "Person", new { person = cst })
            }
        }
    }
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies.Web/Views/Person/ratedcasting.cshtml
@using MovieModel.Lists
@using System.Linq
@model Persons
@{
    Utils.ConnectDatabase();
    var persons = new Persons();
    var auxsep = new Tuple<string, string>("Casting Scraped From", "https://www.themoviedb.org/");
    ViewBag.Title = $"Most Rated Actors";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="col-md-12">
    @Html.DisplayFor(d => auxsep, "separator")
    @{
        var items = 0;
        if (Utils.CurrentUserId() > 0)
        {
            items = 9 * 5;
        }

        var lCast = new List<MovieModel.Entities.Person>();

        if (items > 0)
        {
            lCast = (from cst in persons.Items
                     orderby cst.RatedMovies descending, cst.UserRating descending, cst.Popularity descending
                     select cst).Take(items * 5).ToList();


            foreach (var cst in lCast)
            {
                @Html.Action("Thumbnail", "Person", new { person = cst })
            }
        }
    }
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}